name = "cyberscape"
license = "MIT"
licenselink = "https://github.com/isaksolheim/cyberscape/blob/main/LICENSE"
description = "A lively and fun Hugo theme for creating personal websites ğŸŒ"
homepage = "https://github.com/isaksolheim/cyberscape"
tags = ["personal", "responsive", "tailwind", "blog", "light"]
features = ["markdown", "tailwind"]
min_version = "0.41.0"

[author]
  name = "Isak Solheim"
  homepage = "https://isak.me"
